### ISSUE TITLE
MVP3: Events (CRUD)

### ISSUE THREAD

**Issue by jenkennedy** [jenkennedy/Eventliter#3]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
   - [x] When errors are displayed, the input boxes should not move
- [x] Smooth, bug free navigation
- [x] Adequate and appropriate seeds
- [x] Logged in users can create an event
   - [x] Users can upload photo for event (AWS)
- [x] Users can view events (Event Index Page)
- [x] Users can view a specific event (Event Show Page)
- [x] Users can manage events they've created (Manage Events Page)
   - [x] Logged in users can edit their events (Create/Edit Event Page)
   - [x] Logged in users can delete their events (Manage Events Page)
- [x] Users don't have access to certain features unless they login (create event, register, etc.)

**Comment by rkoron007** [comment]
Just a few styling Things for Event Show Page!

- Quick Fix - it looks like the event title on the events show page is a little grayer then the one you currently have. 
![screen shot 2018-08-17 at 10 36 59 am](https://user-images.githubusercontent.com/32436232/44280457-ac10fd00-a209-11e8-94e4-99099b08e72a.png)

- The description for an event could probably use more margin on the sides so it doesn't look squished. :)
![screen shot 2018-08-17 at 10 41 26 am](https://user-images.githubusercontent.com/32436232/44280623-26da1800-a20a-11e8-940a-6fb048e0b6a1.png)

**Comment by rkoron007** [comment]
Amazing job!!!

**Comment by jenkennedy** [comment]
Just updated the description styling.  For the font color of an event, I used the exact color code that they did.  I think I need to download their custom font information for mine to finally mimic their font properties exactly.

**Comment by rkoron007** [comment]
Looks like there is a heroku error right now- I can check it once that is cleared up though :)
